

// ********RoostGPT********
/*
Test generated by RoostGPT for test java-unit-test using AI Type  and AI Model 

ROOST_METHOD_HASH=divisionStrategy_7c7a8e2257
ROOST_METHOD_SIG_HASH=divisionStrategy_d03805d3bd

"""
Scenario 1: Testing division strategy for sterile bacteria

Details:  
  TestName: testDivisionStrategyForSterileBacteria.
  Description: This test checks the division strategy for a sterile bacteria. A sterile bacteria should always return null as per the division strategy.
Execution:
  Arrange: Create a Bacteria instance and set it as sterile.
  Act: Invoke the divisionStrategy method.
  Assert: Assert that the returned Supplier instance always provides null.
Validation: 
  The assertion verifies that the division strategy for a sterile bacteria always returns null. This is according to the business logic that sterile bacteria cannot reproduce.

Scenario 2: Testing division strategy for non-sterile bacteria with high probability of division

Details:  
  TestName: testDivisionStrategyForNonSterileHighProbBacteria.
  Description: This test checks the division strategy for a non-sterile bacteria with high probability of division. Such a bacteria should usually return a new bacteria instance.
Execution:
  Arrange: Create a Bacteria instance, set it as non-sterile and set a high probability of division.
  Act: Invoke the divisionStrategy method multiple times.
  Assert: Assert that the returned Supplier instance usually provides a new Bacteria instance.
Validation: 
  The assertion verifies that the division strategy for a non-sterile bacteria with high probability of division usually returns a new bacteria. This is according to the business logic that such bacteria usually reproduce.

Scenario 3: Testing division strategy for non-sterile bacteria with low probability of division

Details:  
  TestName: testDivisionStrategyForNonSterileLowProbBacteria.
  Description: This test checks the division strategy for a non-sterile bacteria with low probability of division. Such a bacteria should usually return null.
Execution:
  Arrange: Create a Bacteria instance, set it as non-sterile and set a low probability of division.
  Act: Invoke the divisionStrategy method multiple times.
  Assert: Assert that the returned Supplier instance usually provides null.
Validation: 
  The assertion verifies that the division strategy for a non-sterile bacteria with low probability of division usually returns null. This is according to the business logic that such bacteria usually do not reproduce.

Scenario 4: Testing division strategy for dead bacteria

Details:  
  TestName: testDivisionStrategyForDeadBacteria.
  Description: This test checks the division strategy for a dead bacteria. A dead bacteria should always return null as per the division strategy.
Execution:
  Arrange: Create a Bacteria instance and set it as dead.
  Act: Invoke the divisionStrategy method.
  Assert: Assert that the returned Supplier instance always provides null.
Validation: 
  The assertion verifies that the division strategy for a dead bacteria always returns null. This is according to the business logic that dead bacteria cannot reproduce.
"""
*/

// ********RoostGPT********

package com.solovev.model;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mockito;
import java.util.function.Supplier;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.Objects;
import java.util.Random;

public class BacteriaDivisionStrategyTest {
    private Bacteria bacteria;
    private ConfigurationOfBacteriaBehavior config;
    @BeforeEach
    public void setUp() {
        config = Mockito.mock(ConfigurationOfBacteriaBehavior.class);
        bacteria = new Bacteria(config);
    }
    @Test
    @Tag("valid")
    public void testDivisionStrategyForSterileBacteria() {
        bacteria.setSterile(true);
        Supplier<Bacteria> divisionResult = bacteria.divisionStrategy();
        assertNull(divisionResult.get());
    }
    @Test
    @Tag("valid")
    public void testDivisionStrategyForNonSterileHighProbBacteria() {
        bacteria.setSterile(false);
        Mockito.when(config.probabilityDivision()).thenReturn(1.0);
        Supplier<Bacteria> divisionResult = bacteria.divisionStrategy();
        assertNotNull(divisionResult.get());
    }
    @Test
    @Tag("valid")
    public void testDivisionStrategyForNonSterileLowProbBacteria() {
        bacteria.setSterile(false);
        Mockito.when(config.probabilityDivision()).thenReturn(0.0);
        Supplier<Bacteria> divisionResult = bacteria.divisionStrategy();
        assertNull(divisionResult.get());
    }
    @Test
    @Tag("valid")
    public void testDivisionStrategyForDeadBacteria() {
        bacteria.setDead();
        Supplier<Bacteria> divisionResult = bacteria.divisionStrategy();
        assertNull(divisionResult.get());
    }
}