

// ********RoostGPT********
/*
Test generated by RoostGPT for test java-unit-test using AI Type  and AI Model 

ROOST_METHOD_HASH=divisionStrategy_7c7a8e2257
ROOST_METHOD_SIG_HASH=divisionStrategy_d03805d3bd

"""
Scenario 1: Testing the divisionStrategy method when bacteria is sterile

Details:  
  TestName: testDivisionStrategyWhenBacteriaIsSterile
  Description: This test is designed to validate the divisionStrategy method when the bacteria is sterile. The expected outcome is null as sterile bacteria cannot reproduce.
Execution:
  Arrange: Create a Bacteria object with isSterile set to true.
  Act: Call the divisionStrategy method on the Bacteria object.
  Assert: Assert that the result of the divisionStrategy method is null.
Validation: 
  The assertion verifies that when the bacteria is sterile, the divisionStrategy method returns null. This is expected because sterile bacteria cannot reproduce, hence the null return value.

Scenario 2: Testing the divisionStrategy method when bacteria is not sterile and has a high probability of division

Details:  
  TestName: testDivisionStrategyWithHighProbabilityOfDivision
  Description: This test is designed to check the divisionStrategy method when the bacteria is not sterile and has a high probability of division. The expected outcome is a new bacteria with the same config.
Execution:
  Arrange: Create a Bacteria object with isSterile set to false and a high probability of division.
  Act: Call the divisionStrategy method on the Bacteria object.
  Assert: Assert that the result of the divisionStrategy method is not null and that the returned Bacteria object has the same config as the original.
Validation: 
  The assertion verifies that when the bacteria is not sterile and has a high probability of division, the divisionStrategy method returns a new bacteria with the same config. This is expected because the bacteria can reproduce and produce a new bacteria with the same configuration.

Scenario 3: Testing the divisionStrategy method when bacteria is not sterile but has a low probability of division

Details:  
  TestName: testDivisionStrategyWithLowProbabilityOfDivision
  Description: This test is designed to validate the divisionStrategy method when the bacteria is not sterile but has a low probability of division. The expected outcome is null as the bacteria is unlikely to reproduce.
Execution:
  Arrange: Create a Bacteria object with isSterile set to false and a low probability of division.
  Act: Call the divisionStrategy method on the Bacteria object.
  Assert: Assert that the result of the divisionStrategy method is null.
Validation: 
  The assertion verifies that when the bacteria is not sterile but has a low probability of division, the divisionStrategy method returns null. This is expected because the bacteria is unlikely to reproduce, hence the null return value.
"""
*/

// ********RoostGPT********

package com.solovev.model;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import java.util.function.Supplier;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.*;
import java.util.Objects;
import java.util.Random;

class BacteriaDivisionStrategyTest {
    @Test
    @Tag("valid")
    void testDivisionStrategyWhenBacteriaIsSterile() {
        // Arrange
        Bacteria bacteria = new Bacteria();
        bacteria.setSterile(true);
        // Act
        Supplier<Bacteria> result = bacteria.divisionStrategy();
        // Assert
        assertNull(result.get());
    }
    @Test
    @Tag("valid")
    void testDivisionStrategyWithHighProbabilityOfDivision() {
        // Arrange
        ConfigurationOfBacteriaBehavior config = mock(ConfigurationOfBacteriaBehavior.class);
        when(config.probabilityDivision()).thenReturn(1.0);
        Bacteria bacteria = new Bacteria(config);
        bacteria.setSterile(false);
        // Act
        Supplier<Bacteria> result = bacteria.divisionStrategy();
        // Assert
        assertNotNull(result.get());
        assertEquals(config, result.get().config);
    }
    @Test
    @Tag("valid")
    void testDivisionStrategyWithLowProbabilityOfDivision() {
        // Arrange
        ConfigurationOfBacteriaBehavior config = mock(ConfigurationOfBacteriaBehavior.class);
        when(config.probabilityDivision()).thenReturn(0.0);
        Bacteria bacteria = new Bacteria(config);
        bacteria.setSterile(false);
        // Act
        Supplier<Bacteria> result = bacteria.divisionStrategy();
        // Assert
        assertNull(result.get());
    }
}