
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-unit-test using AI Type  and AI Model

ROOST_METHOD_HASH=notFull_62ed7ce2ab
ROOST_METHOD_SIG_HASH=notFull_24941af784

"""
Scenario 1: Test when PetriDish is not full

Details:
  TestName: testWhenDishIsNotFull
  Description: This test verifies that the method correctly identifies when the PetriDish is not full. The dish is considered full when the fill equals size * size.
Execution:
  Arrange: Create a PetriDish instance with a fill less than size * size.
  Act: Call the notFull() method on the PetriDish instance.
  Assert: Assert that the returned result is true.
Validation:
  The assertion verifies that the method correctly identifies when the PetriDish is not full. This is important to ensure the dish can accept more elements if it's not full.

Scenario 2: Test when PetriDish is full

Details:
  TestName: testWhenDishIsFull
  Description: This test verifies that the method correctly identifies when the PetriDish is full. The dish is considered full when the fill equals size * size.
Execution:
  Arrange: Create a PetriDish instance with a fill equal to size * size.
  Act: Call the notFull() method on the PetriDish instance.
  Assert: Assert that the returned result is false.
Validation:
  The assertion verifies that the method correctly identifies when the PetriDish is full. This is important to ensure the dish doesn't accept more elements if it's full.

Scenario 3: Test when PetriDish is overfilled

Details:
  TestName: testWhenDishIsOverfilled
  Description: This test verifies that the method correctly identifies when the PetriDish is overfilled. The dish is considered overfilled when the fill is greater than size * size.
Execution:
  Arrange: Create a PetriDish instance with a fill greater than size * size.
  Act: Call the notFull() method on the PetriDish instance.
  Assert: Assert that the returned result is false.
Validation:
  The assertion verifies that the method correctly identifies when the PetriDish is overfilled. This is important to ensure the dish doesn't accept more elements if it's overfilled.
"""
*/

// ********RoostGPT********

package com.solovev.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.*;
import java.util.function.Supplier;
import java.util.stream.Collectors;

public class PetriDishNotFullTest {

	@Test
	@Tag("valid")
	public void testWhenDishIsNotFull() {
		// Arrange
		int size = 10;
		int fill = 50; // less than size * size
		PetriDish petriDish = new PetriDish(size, fill);
		// Act
		boolean result = petriDish.notFull();
		// Assert
		assertTrue(result, "Expected the dish to be not full");
	}

	@Test
	@Tag("boundary")
	public void testWhenDishIsFull() {
		// Arrange
		int size = 10;
		int fill = 100; // equals size * size
		PetriDish petriDish = new PetriDish(size, fill);
		// Act
		boolean result = petriDish.notFull();
		// Assert
		assertFalse(result, "Expected the dish to be full");
	}

	@Test
	@Tag("invalid")
	public void testWhenDishIsOverfilled() {
		// Arrange
		int size = 10;
		int fill = 150; // greater than size * size
		PetriDish petriDish = new PetriDish(size, fill);
		// Act
		boolean result = petriDish.notFull();
		// Assert
		assertFalse(result, "Expected the dish to be overfilled");
	}

}