
// ********RoostGPT********
/*
Test generated by RoostGPT for test java-unit-test using AI Type  and AI Model

ROOST_METHOD_HASH=getBacterias_57df7273f6
ROOST_METHOD_SIG_HASH=getBacterias_1e9c31d71d

"""
Scenario 1: Test to check if getBacterias method returns unmodifiable map

Details:
  TestName: testGetBacteriasReturnsUnmodifiableMap
  Description: This test is designed to check if the getBacterias method is returning an unmodifiable map.
Execution:
  Arrange: Create a PetriDish object and populate it with some addresses and bacteria.
  Act: Invoke the getBacterias method on the PetriDish object.
  Assert: Attempt to modify the returned map and catch UnsupportedOperationException.
Validation:
  The assertion aims to verify that the map returned by getBacterias is unmodifiable. The expected result is an UnsupportedOperationException. This test is significant in ensuring that the integrity of the data in the PetriDish object is maintained.

Scenario 2: Test to check if getBacterias method returns correct data

Details:
  TestName: testGetBacteriasReturnsCorrectData
  Description: This test is designed to check if the getBacterias method is returning the correct data.
Execution:
  Arrange: Create a PetriDish object and populate it with some addresses and bacteria.
  Act: Invoke the getBacterias method on the PetriDish object.
  Assert: Compare the returned map with the expected map.
Validation:
  The assertion aims to verify that the map returned by getBacterias is correct. The expected result is that the returned map equals the expected map. This test is significant in ensuring that the getBacterias method is functioning correctly.

Scenario 3: Test to check if getBacterias method returns empty map when no bacteria are present

Details:
  TestName: testGetBacteriasReturnsEmptyMapWhenNoBacteriaPresent
  Description: This test is designed to check if the getBacterias method returns an empty map when there are no bacteria present.
Execution:
  Arrange: Create a PetriDish object without adding any bacteria.
  Act: Invoke the getBacterias method on the PetriDish object.
  Assert: Check if the returned map is empty.
Validation:
  The assertion aims to verify that the map returned by getBacterias is empty when there are no bacteria present. The expected result is that the returned map is empty. This test is significant in ensuring that the getBacterias method handles the scenario of no bacteria correctly.
"""
*/

// ********RoostGPT********

package com.solovev.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;
import java.util.function.Supplier;
import java.util.stream.Collectors;

public class PetriDishGetBacteriasTest {

	PetriDish petriDish;

	Map<Address, Bacteria> expectedMap;

	Bacteria bacteria;

	Address address;

	@BeforeEach
	public void setUp() {
		petriDish = new PetriDish();
		expectedMap = new HashMap<>();
		bacteria = new Bacteria();
		address = new Address(1, 1);
	}

	@Test
	@Tag("valid")
	public void testGetBacteriasReturnsUnmodifiableMap() {
		expectedMap.put(address, bacteria);
		petriDish.addresses.putAll(expectedMap);
		Map<Address, Bacteria> actualMap = petriDish.getBacterias();
		assertThrows(UnsupportedOperationException.class, () -> {
			actualMap.put(new Address(2, 2), new Bacteria());
		});
	}

	@Test
	@Tag("valid")
	public void testGetBacteriasReturnsCorrectData() {
		expectedMap.put(address, bacteria);
		petriDish.addresses.putAll(expectedMap);
		Map<Address, Bacteria> actualMap = petriDish.getBacterias();
		assertEquals(expectedMap, actualMap);
	}

	@Test
	@Tag("boundary")
	public void testGetBacteriasReturnsEmptyMapWhenNoBacteriaPresent() {
		Map<Address, Bacteria> actualMap = petriDish.getBacterias();
		assertTrue(actualMap.isEmpty());
	}

}